#!/bin/sh
# chkconfig: 2345 79 6
# description: Auto associate Elastic IP 2
# processname: aws_elastic_ip2
#

#. /path/to/.ec2env
export JAVA_HOME=/usr/java/default
export EC2_HOME=/usr/local/ec2-api-tools
export PATH=${JAVA_HOME}/bin:${EC2_HOME}/bin:${PATH}
export EC2_PRIVATE_KEY=/path/to/pk-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.pem
export EC2_CERT=/path/to/cert-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.pem

EC2_INSTANCE_ID=`curl -s http://169.254.169.254/latest/meta-data/instance-id`
ELASTIC_IP_ADDRESS=`ec2-describe-instances ${EC2_INSTANCE_ID} | grep -e "^TAG	instance	${EC2_INSTANCE_ID}	Elastic IP	" | cut -f5`

# Carry out specific functions when asked to by the system
case "$1" in
start)
    echo "Assigning Elastic IP Address."
    ec2-associate-address ${ELASTIC_IP_ADDRESS} -i ${EC2_INSTANCE_ID} >/dev/null 2>&1
    ;;

stop)
    echo "Deassigning Elastic IP Address."
    ec2-disassociate-address ${ELASTIC_IP_ADDRESS} >/dev/null 2>&1
    ;;

esac

exit 0
