#!/bin/sh
# chkconfig: 2345 79 6
# description: Auto associate Elastic IP
# processname: aws_elastic_ip
#
ELASTIC_IP_ADDRESS=1.1.1.1

export EC2_HOME=/usr/local/ec2-api-tools
export PATH=${EC2_HOME}/bin:${PATH}
export EC2_PRIVATE_KEY=/path/to/pk-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.pem
export EC2_CERT=/path/to/cert-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.pem

EC2_INSTANCE_ID=`/usr/bin/curl -s http://169.254.169.254/latest/meta-data/instance-id`

# Carry out specific functions when asked to by the system
case "$1" in
start)
    echo "Assigning Elastic IP Address."
    ec2-associate-address ${ELASTIC_IP_ADDRESS} -i ${EC2_INSTANCE_ID} >/dev/null 2>&1
    ;;

stop)
    echo "Deassigning Elastic IP Address."
    ec2-disassociate-address ${ELASTIC_IP_ADDRESS} >/dev/null 2>&1
    ;;

esac

exit 0
